In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN , Dense , Input

In [ ]:
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6],
])

y = np.array([4,5,6,7])

x = x.reshape(-1,3,1) 

print(x)
print(x.shape)

# rnn 은 입력 3차원  (data size, time_steps, features)
model = Sequential([
    Input(shape=(3,1)),
    SimpleRNN(2),
    Dense(1)
])

model.summary()

model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    x,
    y,
    epochs=300,
    verbose=1
)




[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]
(4, 3, 1)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 25.9271
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 25.8964
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 25.8657
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 25.8350
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 25.8044
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 25.7738
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 25.7432
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 25.7127
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 25.6821
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 25.6516
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 25.6212
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 25.5907
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 25.5603
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 25.5300
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 25.4996
Epoch 

In [10]:
# 예측
x_pred = np.array([[5,6,7]]).reshape(-1,3,1)
#pred = model.predict(np.array([[[5],[6],[7]]]))
pred = model.predict(x_pred)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[1.4095024]]


In [ ]:
# 주식 종가 예측

x = np.array([
    [50000, 51000, 52000, 53000],
    [51000, 52000, 53000, 54000],
    [52000, 53000, 54000, 55000]
])

# 다음 날 종가
y = np.array([
    54000,
    55000,
    56000
])

x = x.reshape(-1,4,1)
print(x.shape)
# 모델 생성

# data_size = 3
# time_steps = 4
# features = 1 (종가만 사용)  

model = Sequential([
    Input(shape=(4,1)),
    SimpleRNN(4, activation="relu"),
    Dense(1)
])

model.summary()

model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

#[53000,54000,55000,56000]

(3, 4, 1)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89 (356.00 B)

 Trainable params: 89 (356.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 2261025536.0000
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 2240870400.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 2220674048.0000
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 2200436992.0000
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 2180159744.0000
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 2159844096.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 2139489408.0000
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 2119097728.0000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 2098670080.0000
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 2078206592.0000
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 2057709184.0000
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 2037178496.0000
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 2016615552.0000
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━

In [12]:
# 예측 #[53000,54000,55000,56000]

x_pred = np.array([
    [53000,54000,55000,56000]
])
x_pred = x_pred.reshape(-1,4,1)

pred = model.predict(x_pred)
print("다음날 예상 종가",pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
다음날 예상 종가 [[57114.086]]


In [16]:
# Feature 1 : 온도(Temperature)
# Feature 2 : 습도(Humidity)

# 즉, 3일간의 온도와 습도를 보고 다음 날의 온도를 예측하는 예제

# [온도, 습도]
x = np.array([
    [[20,60],[21,61],[22,62]],
    [[23,63],[24,64],[25,65]],
    [[26,66],[27,67],[28,68]]
])

# 다음 날 온도
y = np.array([
    23,
    26,
    29
])

x = x.reshape(-1,3,2)

print(x.shape)

# ==========================================
# data_size = 3
# time_steps = 3
# features = 2
# ==========================================

model = Sequential([
    Input(shape=(3,2)),
    SimpleRNN(8,activation="relu"),
    Dense(1)
])

model.summary()


model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)


# 예측하시오
#    [[29,69],
#      [30,70],
#      [31,71]]

x_pred = np.array([
    [
        [29,69],
        [30,70],
        [31,71]
     ]
])

pred = model.predict(x_pred)
print("예상온도",pred)


(3, 3, 2)


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_7 (SimpleRNN)        │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 10.1253
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 8.0015
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 6.2582
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 4.8890
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 3.8776
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 3.1950
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.7510
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.5259
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.5039
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.6188
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 2.8006
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.9859
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 3.1271
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 3.1964
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 3.1759
Epoch 16/500
1/1 ━━━

In [19]:
# ==========================================
# 1. 데이터 준비
# ==========================================

# [키(cm), 몸무게(kg), 나이]
x = np.array([
    [[170,60,20], [171,61,21]],
    [[180,70,30], [181,71,31]],
    [[190,80,40], [191,81,41]],
    [[200,90,50], [201,91,51]]
])

# 다음 해 키
y = np.array([
    172,
    182,
    192,
    202
])

x = x.reshape(4,2,3)
print(x.shape)

# ==========================================
# data_size = 4
# time_steps = 2
# features = 3
# ==========================================
model = Sequential([
    Input(shape=(2,3)),
    SimpleRNN(8,activation="relu"),
    Dense(1)
])

model.summary()

model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

x_pred = np.array([
    [
        [210,95,25],
        [211,96,26]
    ]
])

pred = model.predict(x_pred)
print(pred)


(4, 2, 3)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_9 (SimpleRNN)        │ (None, 8)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 105 (420.00 B)

 Trainable params: 105 (420.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 623.6967
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 569.9978
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 519.4365
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 472.1478
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 427.4680
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 385.4256
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 346.0490
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 309.3599
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 275.9030
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 245.3324
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 217.5476
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 192.2174
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 169.2999
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 148.7417
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - l