In [12]:
import numpy as np

arr =  np.array([10, 20, 30, 40, 50])
print(arr)

# 30보다 큰 값만 뽑아 내시오.
# for value in arr:
    
#     if value > 30:
#         print(value)

# 그런데 넘파이 배열 에서는 for문을 돌리면 왕따 당함 
# for 문 안돌리려고 numpy 배열 쓰는 거임 ㅋㅋㅋ

condition = arr > 30
print(condition) #[False False False  True  True]
#result = arr[condition]
result = arr[[False ,False, False,  True , True]]
print(result)


print(arr[arr > 30])

# 조건 : 짝수만 선택
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[arr % 2 == 0]) #[ 2  4  6  8 10]

# 1부터 1000까지의 배열을 만들고 그중에서 7의 배수이자 11의 배수인 숫자들만 뽑아내시오.
#[ 77 154 231 308 385 462 539 616 693 770 847 924]
arr = np.arange(1,1001)
#NumPy 배열 연산에서는 | & (파이프 기호) 
#파이썬 기본 문법은 and or
print(arr[ (arr % 7 == 0) & (arr % 11 ==0) ])

# 1부터 1000까지의 배열을 만들고 그중에서 7의 배수이거나 
# 또는 11의 배수인 숫자들만 뽑아내시오.
arr = np.arange(1,1001)
print(arr[ (arr % 7 == 0) | (arr % 11 ==0) ])

# 1부터 1000까지의 배열에서 짝수이면서 100의 배수
# [ 100  200  300  400  500  600  700  800  900 1000]  
arr = np.arange(1,1001)
print(arr[   (arr % 2  == 0) & (arr % 100  == 0)    ])


[10 20 30 40 50]
[False False False  True  True]
[40 50]
[40 50]
[ 2  4  6  8 10]
[ 77 154 231 308 385 462 539 616 693 770 847 924]
[  7  11  14  21  22  28  33  35  42  44  49  55  56  63  66  70  77  84
  88  91  98  99 105 110 112 119 121 126 132 133 140 143 147 154 161 165
 168 175 176 182 187 189 196 198 203 209 210 217 220 224 231 238 242 245
 252 253 259 264 266 273 275 280 286 287 294 297 301 308 315 319 322 329
 330 336 341 343 350 352 357 363 364 371 374 378 385 392 396 399 406 407
 413 418 420 427 429 434 440 441 448 451 455 462 469 473 476 483 484 490
 495 497 504 506 511 517 518 525 528 532 539 546 550 553 560 561 567 572
 574 581 583 588 594 595 602 605 609 616 623 627 630 637 638 644 649 651
 658 660 665 671 672 679 682 686 693 700 704 707 714 715 721 726 728 735
 737 742 748 749 756 759 763 770 777 781 784 791 792 798 803 805 812 814
 819 825 826 833 836 840 847 854 858 861 868 869 875 880 882 889 891 896
 902 903 910 913 917 924 931 935 938 945 946 952 957 959 966 968 

In [18]:
#팬시 인덱싱
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr[2])

# 일반 인덱싱 → 하나 선택
# 슬라이싱 → 연속 선택
# 팬시 인덱싱 → 원하는 위치 여러 개 선택

#Fancy Indexing(팬시 인덱싱)은 인덱스로 리스트나 배열을 전달해서 원하는 위치의 값들을 한 번에 선택하는 방식
print(arr[ [0,2,4] ])
print(arr[ [4,1,3] ])
print(arr[ [1,1,1] ])

#불린 인덱싱과 팬시 인덱싱의 차이

# 불린 인덱싱 조건 arr > 30 조건선택
# 펜시 인덱싱 arr[[0,2]] 위치선택 

import numpy as np

scores = np.array([
 [80,90,100],
 [70,60,80],
 [95,85,90]
])

scores[ [0,2] ]
print(scores[  : , [0,2] ])

30
[10 30 50]
[50 20 40]
[20 20 20]
[[ 80 100]
 [ 70  80]
 [ 95  90]]
