In [7]:
# 넘파이 정렬

import numpy as np

arr = np.random.randint(10,size=10)
# 원본을 바꿈 => arr.sort()
print(arr)
# print(arr.sort())
# print(arr) # 원본 값을 바꿈

# 원본에 영향을 주지 않는다.
print(np.sort(arr))
print(arr)

[5 7 4 4 4 9 7 2 4 9]
[2 4 4 4 4 5 7 7 9 9]
[5 7 4 4 4 9 7 2 4 9]


In [9]:
#내림 차순
print(np.sort(arr)[::-1])
arr2 = np.sort(arr)[::-1]
print(arr2)

[9 9 7 7 5 4 4 4 4 2]
[9 9 7 7 5 4 4 4 4 2]


In [24]:
np.random.seed(42)
# 2차원 배열 정렬
arr = np.random.randint(15,size=(3,4))
print(arr)

# 행단위 정렬
print(np.sort(arr,axis=1))

# 열단위 정렬
print(np.sort(arr,axis=0))

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]]
[[ 3  6 12 14]
 [ 4  7 10 12]
 [ 2  6  6  9]]
[[ 6  3  2  4]
 [ 6  7 12  6]
 [10  9 12 14]]
