In [1]:
import numpy as np

arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.reshape(3,4)
print(arr) # 원본은 바꾸지 않음

# 이 차원은 네가 알아서 계산해줘
arr.reshape(-1,4)
arr.reshape(2,-1)

arr = np.array([
                    [1, 2, 3], 
                    [0, 1, 4]
               ])

arr.flatten() # 1차원 배열로 만드는 함수


[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([1, 2, 3, 0, 1, 4])

In [8]:
campaigns = [
    {"name": "검색광고", "cost": 100000, "sales": 350000},
    {"name": "SNS광고", "cost": 200000, "sales": 180000},
    {"name": "배너광고", "cost": 150000, "sales": 600000}
]

def print_campaign(ad):
    print("광고명:", ad["name"])
    print("광고비:", ad["cost"])
    print("매출:", ad["sales"])
    print("-----")

for campaign in campaigns:
    print_campaign(campaign)

광고명: 검색광고
광고비: 100000
매출: 350000
-----
광고명: SNS광고
광고비: 200000
매출: 180000
-----
광고명: 배너광고
광고비: 150000
매출: 600000
-----
